//@version=5
strategy('EMA cross And RSI', overlay=true, initial_capital=2500)

// กำหนดขนาดคำสั่ง
tradeSize = input.int(100, title='Trade Size', minval=1)

var float stopLoss = na

// Input parameters
shortEMA = input(7, title='Short EMA Period')
longEMA = input(14, title='Long EMA Period')
ema100 = input(100, title='EMA 100 Period')  // Adding input for EMA 100

// RSI
rsiLength = input(14, title='RSI Length')
rsiValue = ta.rsi(close, rsiLength)

// Calculate EMAs
emaShort = ta.ema(close, shortEMA)
emaLong = ta.ema(close, longEMA)
ema100Value = ta.ema(close, ema100)  // Calculate EMA 100

// Plot EMAs on the chart
plot(emaShort, color=color.rgb(253, 156, 156), title='Short EMA')
plot(emaLong, color=color.rgb(37, 204, 22), title='Long EMA')

// // Plot EMA 100 on the chart
plot(ema100Value, color=color.rgb(90, 23, 134), title='EMA 100')

// Strategy logic 
buyCondition = ta.crossover(emaShort, emaLong) and emaLong < ema100Value and rsiValue > 55  // เพิ่มเงื่อนไขในการตรวจสอบ emaShort ตัดกับ emaLong และ emaLong อยู่ใต้ ema100Value
sellCondition = ta.crossunder(emaShort, emaLong) and emaLong > ema100Value and (rsiValue < 35 or rsiValue > 65 or ta.crossunder(ema100Value, emaShort))
xxxCondition = (ta.crossunder(emaShort, emaLong) and emaLong < ema100Value) and (rsiValue < 35 or rsiValue > 65)


// กำหนดการเข้า-ออกตลาด
if buyCondition
    if strategy.position_size == 0.0
        stopLoss := close * 0.1
        stopLoss
    strategy.entry('Buy', strategy.long, qty=tradeSize)
    label.new(bar_index, high, "Buy: " + str.tostring(close), textcolor=color.white)
    strategy.exit("exit1", "Buy", stop = stopLoss, qty=tradeSize)

if sellCondition
    strategy.close('Buy')
    label.new(bar_index, high, "Sell: " + str.tostring(close), textcolor=color.white)

// Plot buy and sell signals on the chart
plotshape(series=buyCondition, title='Buy Signal', color=color.rgb(137, 197, 122, 12), style=shape.labelup, location=location.belowbar, text='Buy')
plotshape(series=sellCondition, title='Sell Signal', color=color.new(color.red, 0), style=shape.labeldown, location=location.abovebar, text='Sell')
// plotshape(series=xxxCondition, title='XXX Sell Signal', color=color.new(#7903ff, 0), style=shape.labeldown, location=location.abovebar, text='xxx')



